// <auto-generated />
using Generator.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Generator.Domain.Migrations.Project
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Generator.Domain.Core.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DBConnectionString")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsThereIdentity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsThereRole")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsThereUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolutionName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleEntityId")
                        .IsUnique();

                    b.HasIndex("UserEntityId")
                        .IsUnique();

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            DBConnectionString = "Data Source=.; Initial Catalog=MyGeneratedDatabase; Integrated Security=SSPI; Trusted_Connection=True; TrustServerCertificate=True;",
                            IsThereIdentity = true,
                            IsThereRole = false,
                            IsThereUser = false,
                            Path = "C:\\GeneratedProjects",
                            ProjectName = "MyProject",
                            SolutionName = "MyProject"
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.CrudType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CrudTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 2,
                            Control = false,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 3,
                            Control = false,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 4,
                            Control = false,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.DeleteBehaviorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeleteBehaviorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            Name = "Cascade"
                        },
                        new
                        {
                            Id = 2,
                            Control = false,
                            Name = "ClientCascade"
                        },
                        new
                        {
                            Id = 3,
                            Control = false,
                            Name = "Restrict"
                        },
                        new
                        {
                            Id = 4,
                            Control = false,
                            Name = "ClientSetNull"
                        },
                        new
                        {
                            Id = 5,
                            Control = false,
                            Name = "ClientNoAction"
                        },
                        new
                        {
                            Id = 6,
                            Control = false,
                            Name = "SetNull"
                        },
                        new
                        {
                            Id = 7,
                            Control = false,
                            Name = "NoAction"
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Dto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrudTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RelatedEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CrudTypeId");

                    b.HasIndex("RelatedEntityId");

                    b.ToTable("Dtos");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.DtoField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DtoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceFieldId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DtoId");

                    b.HasIndex("SourceFieldId");

                    b.ToTable("DtoFields");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.DtoFieldRelations", b =>
                {
                    b.Property<int>("DtoFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.HasKey("DtoFieldId", "RelationId", "SequenceNo");

                    b.HasIndex("RelationId");

                    b.ToTable("DtoFieldRelations");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archivable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Auditable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BasicResponseDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeleteDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DetailResponseDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReportDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeletable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateDtoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BasicResponseDtoId");

                    b.HasIndex("CreateDtoId");

                    b.HasIndex("DeleteDtoId");

                    b.HasIndex("DetailResponseDtoId");

                    b.HasIndex("ReportDtoId");

                    b.HasIndex("UpdateDtoId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Filterable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("FieldTypeId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.FieldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceTypeId");

                    b.ToTable("FieldTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            Name = "Int",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Control = false,
                            Name = "String",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Control = false,
                            Name = "Long",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Control = false,
                            Name = "Float",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Control = false,
                            Name = "Double",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Control = false,
                            Name = "Bool",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Control = false,
                            Name = "Char",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Control = false,
                            Name = "Byte",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Control = false,
                            Name = "DateTime",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Control = false,
                            Name = "DateOnly",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Control = false,
                            Name = "Guid",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Control = false,
                            Name = "TimeSpan",
                            SourceTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Control = false,
                            Name = "TimeOnly",
                            SourceTypeId = 1
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.FieldTypeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldTypeSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            Name = "Base"
                        },
                        new
                        {
                            Id = 2,
                            Control = false,
                            Name = "Entity"
                        },
                        new
                        {
                            Id = 3,
                            Control = false,
                            Name = "Dto"
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeleteBehaviorTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForeignEntityVirPropName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ForeignFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryEntityVirPropName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeleteBehaviorTypeId");

                    b.HasIndex("ForeignFieldId");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("PrimaryFieldId", "ForeignFieldId")
                        .IsUnique();

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.RelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RelationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            Name = "OneToOne"
                        },
                        new
                        {
                            Id = 2,
                            Control = false,
                            Name = "OneToMany"
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Validation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DtoFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidatorTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DtoFieldId");

                    b.HasIndex("ValidatorTypeId");

                    b.ToTable("Validations");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.ValidationParam", b =>
                {
                    b.Property<int>("ValidationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidatorTypeParamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ValidationId", "ValidatorTypeParamId");

                    b.HasIndex("ValidatorTypeParamId");

                    b.ToTable("ValidationParams");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.ValidatorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ValidatorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            Description = "Field cannot be empty",
                            Name = "NotEmpty"
                        },
                        new
                        {
                            Id = 2,
                            Control = false,
                            Description = "Field cannot be null",
                            Name = "NotNull"
                        },
                        new
                        {
                            Id = 3,
                            Control = false,
                            Description = "Field cannot be ...",
                            Name = "NotEqual"
                        },
                        new
                        {
                            Id = 4,
                            Control = false,
                            Description = "Field cannot exceed maximum length",
                            Name = "MaxLength"
                        },
                        new
                        {
                            Id = 5,
                            Control = false,
                            Description = "Value must be within a specific range",
                            Name = "Range"
                        },
                        new
                        {
                            Id = 6,
                            Control = false,
                            Description = "Field must have a minimum number of characters",
                            Name = "MinLength"
                        },
                        new
                        {
                            Id = 7,
                            Control = false,
                            Description = "Field must match a regular expression",
                            Name = "Regex"
                        },
                        new
                        {
                            Id = 8,
                            Control = false,
                            Description = "Value must be greater than a specific number",
                            Name = "GreaterThan"
                        },
                        new
                        {
                            Id = 9,
                            Control = false,
                            Description = "Value must be less than a specific number",
                            Name = "LessThan"
                        },
                        new
                        {
                            Id = 10,
                            Control = false,
                            Description = "Field must be a valid email address",
                            Name = "EmailAddress"
                        },
                        new
                        {
                            Id = 11,
                            Control = false,
                            Description = "Field must be a valid credit card number",
                            Name = "CreditCard"
                        },
                        new
                        {
                            Id = 12,
                            Control = false,
                            Description = "Field must be a valid phone number",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 13,
                            Control = false,
                            Description = "Field must be a valid URL",
                            Name = "Url"
                        },
                        new
                        {
                            Id = 14,
                            Control = false,
                            Description = "Field must be a valid date",
                            Name = "Date"
                        },
                        new
                        {
                            Id = 15,
                            Control = false,
                            Description = "Field must be a valid number",
                            Name = "Number"
                        },
                        new
                        {
                            Id = 16,
                            Control = false,
                            Description = "Field mus be a valid guid value",
                            Name = "GuidNotEmpty"
                        },
                        new
                        {
                            Id = 17,
                            Control = false,
                            Description = "Field must have a exact number of characters\", \"Length",
                            Name = "Length"
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.ValidatorTypeParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidatorTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ValidatorTypeId");

                    b.ToTable("ValidatorTypeParams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Control = false,
                            Key = "Value",
                            ValidatorTypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            Control = false,
                            Key = "Max",
                            ValidatorTypeId = 4
                        },
                        new
                        {
                            Id = 3,
                            Control = false,
                            Key = "Min",
                            ValidatorTypeId = 5
                        },
                        new
                        {
                            Id = 4,
                            Control = false,
                            Key = "Max",
                            ValidatorTypeId = 5
                        },
                        new
                        {
                            Id = 5,
                            Control = false,
                            Key = "Min",
                            ValidatorTypeId = 6
                        },
                        new
                        {
                            Id = 6,
                            Control = false,
                            Key = "Pattern",
                            ValidatorTypeId = 7
                        },
                        new
                        {
                            Id = 7,
                            Control = false,
                            Key = "Value",
                            ValidatorTypeId = 8
                        },
                        new
                        {
                            Id = 8,
                            Control = false,
                            Key = "Value",
                            ValidatorTypeId = 9
                        },
                        new
                        {
                            Id = 9,
                            Control = false,
                            Key = "Value",
                            ValidatorTypeId = 17
                        });
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.AppSetting", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.Entity", "RoleEntity")
                        .WithOne("AsRoleAppSetting")
                        .HasForeignKey("Generator.Domain.Core.Entities.AppSetting", "RoleEntityId");

                    b.HasOne("Generator.Domain.Core.Entities.Entity", "UserEntity")
                        .WithOne("AsUserAppSetting")
                        .HasForeignKey("Generator.Domain.Core.Entities.AppSetting", "UserEntityId");

                    b.Navigation("RoleEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Dto", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.CrudType", "CrudType")
                        .WithMany("Dtos")
                        .HasForeignKey("CrudTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.Entity", "RelatedEntity")
                        .WithMany("Dtos")
                        .HasForeignKey("RelatedEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CrudType");

                    b.Navigation("RelatedEntity");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.DtoField", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.Dto", "Dto")
                        .WithMany("DtoFields")
                        .HasForeignKey("DtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.Field", "SourceField")
                        .WithMany("DtoFields")
                        .HasForeignKey("SourceFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dto");

                    b.Navigation("SourceField");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.DtoFieldRelations", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.DtoField", "DtoField")
                        .WithMany("DtoFieldRelations")
                        .HasForeignKey("DtoFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.Relation", "Relation")
                        .WithMany("DtoFieldRelations")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DtoField");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Entity", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.Dto", "BasicResponseDto")
                        .WithMany("BasicResponseEntities")
                        .HasForeignKey("BasicResponseDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Generator.Domain.Core.Entities.Dto", "CreateDto")
                        .WithMany("CreateEntities")
                        .HasForeignKey("CreateDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Generator.Domain.Core.Entities.Dto", "DeleteDto")
                        .WithMany("DeleteEntities")
                        .HasForeignKey("DeleteDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Generator.Domain.Core.Entities.Dto", "DetailResponseDto")
                        .WithMany("DetailResponseEntities")
                        .HasForeignKey("DetailResponseDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Generator.Domain.Core.Entities.Dto", "ReportDto")
                        .WithMany("ReportEntities")
                        .HasForeignKey("ReportDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Generator.Domain.Core.Entities.Dto", "UpdateDto")
                        .WithMany("UpdateEntities")
                        .HasForeignKey("UpdateDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BasicResponseDto");

                    b.Navigation("CreateDto");

                    b.Navigation("DeleteDto");

                    b.Navigation("DetailResponseDto");

                    b.Navigation("ReportDto");

                    b.Navigation("UpdateDto");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Field", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.Entity", "Entity")
                        .WithMany("Fields")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.FieldType", "FieldType")
                        .WithMany("Fields")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.FieldType", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.FieldTypeSource", "SourceType")
                        .WithMany("FieldTypes")
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Relation", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.DeleteBehaviorType", "DeleteBehaviorType")
                        .WithMany("Relations")
                        .HasForeignKey("DeleteBehaviorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.Field", "ForeignField")
                        .WithMany("RelationsForeign")
                        .HasForeignKey("ForeignFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.Field", "PrimaryField")
                        .WithMany("RelationsPrimary")
                        .HasForeignKey("PrimaryFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.RelationType", "RelationType")
                        .WithMany("Relations")
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeleteBehaviorType");

                    b.Navigation("ForeignField");

                    b.Navigation("PrimaryField");

                    b.Navigation("RelationType");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Validation", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.DtoField", "DtoField")
                        .WithMany("Validations")
                        .HasForeignKey("DtoFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.ValidatorType", "ValidatorType")
                        .WithMany("Validations")
                        .HasForeignKey("ValidatorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DtoField");

                    b.Navigation("ValidatorType");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.ValidationParam", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.Validation", "Validation")
                        .WithMany("ValidationParams")
                        .HasForeignKey("ValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Generator.Domain.Core.Entities.ValidatorTypeParam", "ValidatorTypeParam")
                        .WithMany("ValidationParams")
                        .HasForeignKey("ValidatorTypeParamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Validation");

                    b.Navigation("ValidatorTypeParam");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.ValidatorTypeParam", b =>
                {
                    b.HasOne("Generator.Domain.Core.Entities.ValidatorType", "ValidatorType")
                        .WithMany("ValidatorTypeParams")
                        .HasForeignKey("ValidatorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ValidatorType");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.CrudType", b =>
                {
                    b.Navigation("Dtos");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.DeleteBehaviorType", b =>
                {
                    b.Navigation("Relations");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Dto", b =>
                {
                    b.Navigation("BasicResponseEntities");

                    b.Navigation("CreateEntities");

                    b.Navigation("DeleteEntities");

                    b.Navigation("DetailResponseEntities");

                    b.Navigation("DtoFields");

                    b.Navigation("ReportEntities");

                    b.Navigation("UpdateEntities");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.DtoField", b =>
                {
                    b.Navigation("DtoFieldRelations");

                    b.Navigation("Validations");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Entity", b =>
                {
                    b.Navigation("AsRoleAppSetting");

                    b.Navigation("AsUserAppSetting");

                    b.Navigation("Dtos");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Field", b =>
                {
                    b.Navigation("DtoFields");

                    b.Navigation("RelationsForeign");

                    b.Navigation("RelationsPrimary");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.FieldType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.FieldTypeSource", b =>
                {
                    b.Navigation("FieldTypes");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Relation", b =>
                {
                    b.Navigation("DtoFieldRelations");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.RelationType", b =>
                {
                    b.Navigation("Relations");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.Validation", b =>
                {
                    b.Navigation("ValidationParams");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.ValidatorType", b =>
                {
                    b.Navigation("Validations");

                    b.Navigation("ValidatorTypeParams");
                });

            modelBuilder.Entity("Generator.Domain.Core.Entities.ValidatorTypeParam", b =>
                {
                    b.Navigation("ValidationParams");
                });
#pragma warning restore 612, 618
        }
    }
}
